// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce.Data;

#nullable disable

namespace ecommerce.Data.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20260709204108_AddMoreSeedProducts")]
    partial class AddMoreSeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ecommerce.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shirts"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sweaters"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hoodies"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shorts"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lucia@example.com",
                            Name = "Lucia Rodriguez"
                        },
                        new
                        {
                            Id = 2,
                            Email = "juan@example.com",
                            Name = "Juan Perez"
                        },
                        new
                        {
                            Id = 3,
                            Email = "paco@example.com",
                            Name = "Paco Sanchez"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana@example.com",
                            Name = "Ana Lopez"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.OrderTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTracking");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "Black",
                            Description = "100% cotton graphic t-shirt",
                            Name = "Graphic Tee",
                            Price = 400m,
                            Size = 2,
                            Sku = "TS-001"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "White",
                            Description = "Plain everyday t-shirt",
                            Name = "Basic Tee",
                            Price = 300m,
                            Size = 1,
                            Sku = "TS-002"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Color = "Blue",
                            Description = "Casual button-up shirt",
                            Name = "Button-Up Shirt",
                            Price = 550m,
                            Size = 2,
                            Sku = "SH-001"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Color = "Beige",
                            Description = "Lightweight linen shirt",
                            Name = "Linen Shirt",
                            Price = 650m,
                            Size = 3,
                            Sku = "SH-002"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Color = "Cream",
                            Description = "Soft knit crewneck sweater",
                            Name = "Crewneck Sweater",
                            Price = 750m,
                            Size = 2,
                            Sku = "SW-001"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Color = "Brown",
                            Description = "Warm turtleneck sweater",
                            Name = "Turtleneck Sweater",
                            Price = 850m,
                            Size = 3,
                            Sku = "SW-002"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Color = "Gray",
                            Description = "Cotton blend oversized hoodie",
                            Name = "Oversized Hoodie",
                            Price = 800m,
                            Size = 3,
                            Sku = "HD-001"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Color = "Navy",
                            Description = "Comfortable zip-up hoodie",
                            Name = "Zip-Up Hoodie",
                            Price = 850m,
                            Size = 2,
                            Sku = "HD-002"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Color = "Blue",
                            Description = "Classic dark denim jeans",
                            Name = "Dark Denim Jeans",
                            Price = 600m,
                            Size = 4,
                            Sku = "JN-001"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Color = "Khaki",
                            Description = "Lightweight casual shorts",
                            Name = "Casual Shorts",
                            Price = 450m,
                            Size = 2,
                            Sku = "ST-001"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Entities.ProductInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStock = 20,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentStock = 18,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            CurrentStock = 15,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CurrentStock = 10,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            CurrentStock = 12,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            CurrentStock = 9,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            CurrentStock = 12,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            CurrentStock = 11,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            CurrentStock = 8,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            CurrentStock = 14,
                            ProductId = 10
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Order", b =>
                {
                    b.HasOne("ecommerce.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("ecommerce.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecommerce.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.OrderTracking", b =>
                {
                    b.HasOne("ecommerce.Data.Entities.Order", "Order")
                        .WithMany("TrackingHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Product", b =>
                {
                    b.HasOne("ecommerce.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.ProductInventory", b =>
                {
                    b.HasOne("ecommerce.Data.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("ecommerce.Data.Entities.ProductInventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("TrackingHistory");
                });

            modelBuilder.Entity("ecommerce.Data.Entities.Product", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
